name: wind_http
description: A sample command-line application with basic argument parsing.
version: 0.0.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.3

# Add regular dependencies here.
dependencies:
  http: ^1.2.2
  built_value: ^8.9.2
  built_collection: ^5.1.1
  logging: ^1.2.0
  qs_dart: ^1.2.4
  wind_utils: ^0.0.1



dev_dependencies:
  args: ^2.4.2
  lints: ^4.0.0
  test: ^1.24.0
  mockito: ^5.4.4
  build_runner: ^2.4.13
  built_value_generator: ^8.9.2
